# Generated by Django 5.0.4 on 2024-05-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
    ]
