# Generated by Django 5.0.4 on 2024-06-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_category_section_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
